### ISSUE TITLE
Finalise FlowTypeCheck

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#995]
The new mechanism for type inference for expressions needs a bunch of things still:

- [x] 1. Tidy up the `apply()` method
- [x] 2. Resolve issues around binding against unions (e.g. `int|bool` again `S|T`) (see #994)
- [x] 3. Resolve equality issue?
- [x] 4. Remove `LifetimeRelation` from `SubtypeOperator` (see #992)
- [x] 4. Implement forward propagation (see #941)
- [x] 5. Retire `AmbiguousCoercionCheck` and `AbstractTypedVisitor` (see #990)
